const retrievedElements = {
    content: document.getElementsByClassName('content')[0],
    mainContent: document.getElementsByClassName('mainContent')[0],
    mainContainer: document.getElementsByClassName('mainContainer')[0],
    hamburgerContainer: document.getElementsByClassName('hamburgerContainer')[0],
    hamburgerContent: document.getElementById('hamburgerContent'),
    hamburgerButton: document.getElementById('hamburger'),
    hamburger: document.getElementById('hamburger'),
    addProject: document.getElementById('addProject'),
    form: document.getElementById('mainForm'),
    header: document.getElementsByClassName('header')[0],
    modal: document.getElementsByClassName('modal')[0],
    modalContent: document.getElementsByClassName('modalContent')[0],
    submit: document.getElementById('submit'),
    taskName: document.getElementById('taskName'),
    dueDate: document.getElementById('dueDate'),
    description: document.getElementById('description'),
    priority: document.getElementById('priority'),
    noTasksContainer: document.getElementById('noTasksContainer'),
    close: document.getElementById('close'),
    dueToday: document.getElementById('today'),
    dueThisWeek: document.getElementById('seven'),
    defaultProject: document.getElementById('defaultProject'),
    taskbar: document.getElementById('taskbar'),
    UIDueDates: document.getElementsByClassName('UIDueDate'),
    UITaskContainers: document.getElementsByClassName('UITaskContainer'),
    all: document.getElementsByClassName('all')[0],
    allLabel: document.getElementById('allLabel'),
    addTask: document.getElementById('addTask'),
    projectModal: document.getElementsByClassName('projectModal')[0],
    projectClose: document.getElementById('projectClose'),
    projectSubmit: document.getElementById('projectSubmit'),
    projectContainer: document.getElementsByClassName('projectContainer')[0],
    project: document.getElementById('project'),
}

const taskArray = []

export { retrievedElements };
export { taskArray };